### ISSUE TITLE
Unhandled error in Deferred - exceptions.TypeError

### ISSUE THREAD

**Issue by ryouiki** [c00w/bitHopper#1]
delag_server() in pool.py is broken

```
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 793, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 194, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 133, in maybeDeferred
    result = f(*args, **kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1141, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1020, in _inlineCallbacks
    result = g.send(result)
  File "C:\Python27\bitHopper\pool.py", line 268, in delag_server
    data = yield work.jsonrpc_call(json_agent, server, set_lp)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1141, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
exceptions.TypeError: jsonrpc_call() takes exactly 4 arguments (3 given)
```

**Comment by c00w** [comment]
Updated in the latest version If you downloaded with git use "git pull" otherwise redownload the compressed file.

EDIT: This was completely wrong. I misread the error to be 4 given 3 expected.

**Comment by c00w** [comment]
To be clear this is actually an old issue from an older version it was fixed a while ago. Updating is a good idea just because a lot more features work now even if you could care less about the delager working.

**Comment by c00w** [comment]
Nope its not. I'm being stupid. It should be fixed now.

**Comment by c00w** [comment]
Oh and sorry about closing the issue multiple times. I keep forgetting the button to comment also closes it.

**Comment by ryouiki** [comment]
OK, this issue is fixed now.
