### ISSUE TITLE
pull_lp() takes exactly 3 arguments (2 given) with AltSliceScheduler

### ISSUE THREAD

**Issue by bitcoindaddy** [c00w/bitHopper#127]
python bitHopper.py --scheduler AltSliceScheduler
...
[10:49:39] RPC request [getwork] submitted to DigBTC.net
[10:49:40] received lp from: digbtc
Traceback (most recent call last):
  File "bitHopper.py", line 298, in <module>
    main()
  File "bitHopper.py", line 294, in main
    reactor.run()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 1165, in run
    self.mainLoop()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 1174, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 796, in runUntilCurrent
    call.func(_call.args, *_call.kw)
exceptions.TypeError: pull_lp() takes exactly 3 arguments (2 given)
[10:49:40] RPC request [getwork] submitted to DigBTC.net

**Comment by c00w** [comment]
Update. Does the error still appear?

**Comment by c00w** [comment]
I think I just fixed it. Update again.

**Comment by c00w** [comment]
This should be fixed. If it appears again reopen. Please.
