### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#2]
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 796, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 125, in maybeDeferred
    result = f(_args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 1014, in unwindGenerator
    return _inlineCallbacks(None, f(_args, *_kwargs), Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 893, in _inlineCallbacks
    result = g.send(result)
  File "pool.py", line 284, in delag_server
    data = yield work.jsonrpc_call(json_agent, server, set_lp)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 1014, in unwindGenerator
    return _inlineCallbacks(None, f(_args, *_kwargs), Deferred())
exceptions.TypeError: jsonrpc_call() takes exactly 4 arguments (3 given)

**Comment by c00w** [comment]
It should be fixed in the latest version.

**Comment by c00w** [comment]
If it isn't tell me. Please.

**Comment by yomismo22** [comment]
so far seams fixed :D
