### ISSUE TITLE
bitHopper exception

### ISSUE THREAD

**Issue by rkozola** [c00w/bitHopper#204]
I am getting the following exception in bitHopper console, after which it gets very unstable

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1141, in
unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1020, in
_inlineCallbacks
    result = g.send(result)
  File "C:\Users\rkozola\Desktop\bitHopper\work.py", line 185, in handle
    work = yield self.jsonrpc_getwork(server, data, request)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1141, in
unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1020, in
_inlineCallbacks
    result = g.send(result)
  File "C:\Users\rkozola\Desktop\bitHopper\work.py", line 163, in jsonrpc_getwor
k
    self.bitHopper.get_new_server(server)
  File "C:\Users\rkozola\Desktop\bitHopper\bitHopper.py", line 120, in get_new_s
erver
    self.pool.get_entry(server)['lag'] = True
exceptions.TypeError: 'NoneType' object does not support item assignment
```

**Comment by rkozola** [comment]
another exception

```
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\rkozola\Desktop\bitHopper\bitHopper.py", line 250, in <module>
    main()
  File "C:\Users\rkozola\Desktop\bitHopper\bitHopper.py", line 246, in main
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1162, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1174, in m
ainLoop
    self.doIteration(t)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 1
04, in doSelect
    [], timeout)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 4
0, in win32select
    r, w, e = select.select(r, w, w, timeout)
exceptions.ValueError: too many file descriptors in select()
```

**Comment by c00w** [comment]
The second one is being worked on. I added something so that when the first error happens again we get more info.

**Comment by c00w** [comment]
If it appears again using latest please tell me.

**Comment by sdogi** [comment]
I'm getting something very similar to the second one. It happens with latest but also happened few revisions back because I woke up to the same thing. Basically at some point it hits some sort of loop that spams only these errors and it is impossible kill bithopper. It also consumes 100% of one of my cpu cores. This seems to happen with few hours.

2011-08-18 19:29:34+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:34+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:34+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:34+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:34+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:34+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:34+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:35+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:35+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:35+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:35+0300 [-] Malformed file descriptor found.  Preening lists.
2011-08-18 19:29:35+0300 [-] Unhandled Error
    Traceback (most recent call last):
      File "bitHopper.py", line 266, in <module>
        main()
      File "bitHopper.py", line 262, in main
        reactor.run()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1162, in run
        self.mainLoop()
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\base.py", line 1174, in mainLoop
        self.doIteration(t)
    --- <exception caught here> ---
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 104, in doSelect
        [], timeout)
      File "C:\Documents and Settings\Allan\Application Data\Python\Python27\site-packages\twisted\internet\selectreactor.py", line 40, in win32select
        r, w, e = select.select(r, w, w, timeout)
    exceptions.ValueError: too many file descriptors in select()

2011-08-18 19:29:35+0300 [-] Malformed file descriptor found.  Preening lists.

**Comment by c00w** [comment]
Okay. But is the first one appearing again?

**Comment by c00w** [comment]
Both of these exceptions should no longer appear. I'm closing the issue. If they do appear with the latest version please reopen the issue or make a new one.
