### ISSUE TITLE
Unhandled Error Shutting miners down

### ISSUE THREAD

**Issue by hawks5999** [c00w/bitHopper#212]
2011-08-17 23:40:01-0700 [HTTP11ClientProtocol,client] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.KeyError: 'lp_address'

2011-08-17 23:40:01-0700 [HTTP11ClientProtocol,client] 'Lagging. :digbtc'
2011-08-17 23:40:01-0700 [HTTP11ClientProtocol,client] Unhandled error in Deferr
ed:
2011-08-17 23:40:01-0700 [HTTP11ClientProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 3
88, in errback
            self._startRunCallbacks(fail)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 4
55, in _startRunCallbacks
            self._runCallbacks()
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 5
42, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1
076, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1
018, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 3
50, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "C:\BTC\bitHopper\work.py", line 184, in handle
            work = yield self.jsonrpc_getwork(server, data, request)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1
020, in _inlineCallbacks
            result = g.send(result)
          File "C:\BTC\bitHopper\work.py", line 162, in jsonrpc_getwork
            self.bitHopper.get_new_server(server)
          File "C:\BTC\bitHopper\bitHopper.py", line 132, in get_new_server
            self.server_update()
          File "C:\BTC\bitHopper\bitHopper.py", line 136, in server_update
            if self.scheduler.server_update():
          File "C:\BTC\bitHopper\scheduler.py", line 184, in server_update
            shares,info = self.server_to_btc_shares(current)
          File "C:\BTC\bitHopper\scheduler.py", line 71, in server_to_btc_shares

```
        shares = info['shares']
    exceptions.KeyError: 'shares'
```

**Comment by c00w** [comment]
Hmmm. I'm not sure why this happened. But shutting down throws exceptions into all sorts of weird places.

**Comment by hawks5999** [comment]
This seems to have been resolved in recent updates ... at least it hasn't repro'd
