### ISSUE TITLE
Unhandled error in bithopper.py

### ISSUE THREAD

**Issue by annawaw** [c00w/bitHopper#265]
BH started throing the following exception in an infinite loop:

Unhandled Error
Traceback (most recent call last):
  File "d:\c00w-bitHopper\bitHopper.py", line 269, in <module>
    main()
  File "d:\c00w-bitHopper\bitHopper.py", line 265, in main
    reactor.run()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1162, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1174, in m
ainLoop
    self.doIteration(t)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 1
04, in doSelect
    [], timeout)
  File "c:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 4
0, in win32select
    r, w, e = select.select(r, w, w, timeout)
exceptions.ValueError: too many file descriptors in select()
U

---

I'm using BH 0.2.1-0. It happened when I was trying to use 3 cgminers instead of poclbm.

**Comment by sdogi** [comment]
These are known issues with twisted(known by twisted developers too) and this is one of the reasons why bitHopper went over to eventlets. Twisted version isn't able to handle too many workers. Although we just went over to eventlets and there is one serious bug that we are going to try to fix ASAP I would advise you to upgrade.

If we can't figure this out by today then I'll make a small temporary wrapper that will restart new bitHopper every 30-60 minutes to keep it operational.

**Comment by c00w** [comment]
This is a known issue with twisted python on windows and the reason we moved to eventlet.

**Comment by c00w** [comment]
Its currently fixed in the latest version so I am closing the issue.
