### ISSUE TITLE
Unhandled error in Deferred:

### ISSUE THREAD

**Issue by yomismo22** [c00w/bitHopper#27]
python bitHopper.py
Unhandled error in Deferred:
Traceback (most recent call last):
  File "bitHopper.py", line 332, in <module>
    main()
  File "bitHopper.py", line 324, in main
    update_call.start(60)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/task.py", line 163, in start
    self()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/task.py", line 194, in **call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 125, in maybeDeferred
    result = f(_args, *_kw)
  File "/home/yo/bitHopper/pool.py", line 186, in update_api_servers
    d = work.get(bitHopper.json_agent,info['api_address'])
exceptions.KeyError: 'api_address'
[19:41:14] RPC request [] submitted to BTC Guild

**Comment by c00w** [comment]
Thats a wierd error for three reasons. 1) it shouldnt be pulling btcg data. 2) It has an api_address.
If you made modifications check the the pool.py info for btcguild has api_address spelled as api_address

**Comment by c00w** [comment]
I'm going to close this issue. If its still appearing Tell me or respond or something.
