### ISSUE TITLE
Indentation Error

### ISSUE THREAD

**Issue by tylersatre** [c00w/bitHopper#308]
```
Traceback (most recent call last):
  File "C:\Users\Case\Desktop\bithopper\bitHopper.py", line 32, in <module>
    import lp
  File "C:\Users\Case\Desktop\bithopper\lp.py", line 24
    out_words.append(in_buf[i:i+4])
            ^
```

IndentationError: expected an indented block

I get the above error when trying to run the latest pull (0.2.4.4-98)

**Comment by c00w** [comment]
It should be fixed in the latest. 2.4.4-101
