### ISSUE TITLE
phoenix 1.6.2 may be broken.

### ISSUE THREAD

**Issue by c00w** [c00w/bitHopper#338]
Traceback (most recent call last):
  File "C:\Python27\c00w-bitHopper-b79fb2f\lp.py", line 148, in receive
    response = json.loads(body)
  File "C:\Python27\lib\json__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenpool.py", line 80, in _spawn_n_impl
    func(_args, *_kwargs)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 514, in process_request
    proto = self.protocol(socket, address, self)
  File "C:\Python27\lib\SocketServer.py", line 641, in __init__
    self.finish()
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 456, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "C:\Python27\lib\SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 283, in sendall
    tail = self.send(data, flags)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 269, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenpool.py", line 80, in _spawn_n_impl
    func(_args, *_kwargs)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 514, in process_request
    proto = self.protocol(socket, address, self)
  File "C:\Python27\lib\SocketServer.py", line 641, in __init__
    self.finish()
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 456, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "C:\Python27\lib\SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 283, in sendall
    tail = self.send(data, flags)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 269, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "C:\Python27\c00w-bitHopper-b79fb2f\lp.py", line 148, in receive
    response = json.loads(body)
  File "C:\Python27\lib\json__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenpool.py", line 80, in _spawn_n_impl
    func(_args, *_kwargs)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 514, in process_request
    proto = self.protocol(socket, address, self)
  File "C:\Python27\lib\SocketServer.py", line 641, in __init__
    self.finish()
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\wsgi.py", line 456, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "C:\Python27\lib\SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 283, in sendall
    tail = self.send(data, flags)
  File "C:\Python27\c00w-bitHopper-b79fb2f\eventlet\greenio.py", line 269, in send
    total_se

**Comment by c00w** [comment]
It appears to be working.
