### ISSUE TITLE
KeyError: spam across console

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#355]
Traceback (most recent call last):
  File "/home/alex/bitHopper/eventlet/hubs/hub.py", line 336, in fire_timers
    timer()
  File "/home/alex/bitHopper/eventlet/hubs/timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "/home/alex/bitHopper/scheduler.py", line 35, in bitHopper_server_update
    self.bitHopper.server_update()
  File "bitHopper.py", line 145, in server_update
    if self.scheduler.server_update():
  File "/home/alex/bitHopper/scheduler.py", line 283, in server_update
    current = self.sliceinfo[self.bitHopper.pool.get_current()]
KeyError: 'eligius'

getting this allot in last ver

**Comment by c00w** [comment]
Should be fixed now.
