### ISSUE TITLE
BUG: SimpleSliceSched not working in latest

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#365]
hey c00w i'm getting this at start-up when i try to use simple sched and bH doesn't start at all

[21:30:18] Selecting scheduler: SimpleSliceScheduler
Traceback (most recent call last):
  File "bitHopper.py", line 294, in <module>
    main()
  File "bitHopper.py", line 250, in main
    bithopper_instance.scheduler = s(bithopper_instance)
  File "/home/alex/bitHopper/scheduler.py", line 218, in **init**
    for server in self.bitHopper.servers:
AttributeError: BitHopper instance has no attribute 'servers'

to be more specific I only change the value in bh.cfg and using --debug launch param

**Comment by c00w** [comment]
Fixed.

**Comment by paraipan** [comment]
thanks c00w
