### ISSUE TITLE
some Error message

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#374]
[22:49:44] Lagging. :triple
Traceback (most recent call last):
  File "C:\bithopper\eventlet\hubs\hub.py", line 336, in fire_timers
    timer()
  File "C:\bithopper\eventlet\hubs\timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "C:\bithopper\work.py", line 221, in handle_store
    merkle_root = work["data"][72:136]
TypeError: 'NoneType' object is not subscriptable

**Comment by Endeavour79** [comment]
Think this happens when a pools is lagging too long/often..

**Comment by c00w** [comment]
This should be fixed now.
