### ISSUE TITLE
Bug: KeyError: 'i0c'

### ISSUE THREAD

**Issue by amrando** [c00w/bitHopper#401]
Using version v0.2.5.1-4-g4951647 with ixc and i0c set to mine (mine_ixc, mine_i0c respectively)

[13:10:14] DB: Checking Database
[13:10:14] LP Module Load
[13:10:14] Loading Config Files
[13:10:14] DB: Checking Database
[13:10:14] Plugin loading mode: manual
[13:10:14] Loading Plugins
[13:10:14] Plugin: hookexample failed reading main config file: No option 'hookexample' in section: 'plugins'
[13:10:14] Plugin: hookexample has been disabled
[13:10:14] [apiangel]  - Check interval: 60
[13:10:14] [apiangel]  - Re-Incarnate interval: 3600
[13:10:14] Plugin: apiangel loaded
[13:10:14] Plugin: lpbot loaded
[13:10:14] Plugin: rpcworklog loaded
[13:10:14] Plugin: test loaded
[13:10:14] Plugin: blockaccuracy has been disabled
[13:10:14] Plugin: poclbm has been disabled
[13:10:14] Plugin: poolblocks has been disabled
[13:10:14] Plugin: backdoor has been disabled
[13:10:14] Plugin: lpworkbench loaded
[13:10:14] Selecting scheduler: DefaultScheduler
Traceback (most recent call last):
  File "./bitHopper.py", line 299, in <module>
    main()
  File "./bitHopper.py", line 269, in main
    bithopper_instance.select_best_server()
  File "./bitHopper.py", line 129, in select_best_server
    server_name = self.scheduler.select_best_server()
  File "/home/miner/bitHopper/scheduler.py", line 184, in select_best_server
    if not self.server_is_valid(server):
  File "/home/miner/bitHopper/scheduler.py", line 125, in server_is_valid
    if self.bitHopper.exchange.profitability[info['coin']] < 1.0:
KeyError: 'i0c'

**Comment by c00w** [comment]
Should be fixed now. The last stable version is v0.2.5.1.
