### ISSUE TITLE
Bug: stats.db

### ISSUE THREAD

**Issue by amrando** [c00w/bitHopper#402]
Using version v0.2.5.2-13-g63c7c23 (newer version than other bug I posted) with ixc and i0c pools mining

after wipe stats.db

[14:13:08] DB: Checking Database
Traceback (most recent call last):
  File "./bitHopper.py", line 305, in <module>
    main()
  File "./bitHopper.py", line 231, in main
    bithopper_instance = BitHopper(options, config)
  File "./bitHopper.py", line 57, in **init**
    self.pool = pool.Pool_Parse(self)
  File "/home/miner/bitHopper/pool.py", line 33, in **init**
    self.loadConfig()
  File "/home/miner/bitHopper/pool.py", line 66, in loadConfig
    self.servers[pool] = pool_class.Pool(pool, dict(parser.items(pool)), self.bitHopper)
  File "/home/miner/bitHopper/pool_class.py", line 13, in **init**
    self._parse(attribute_dict)
  File "/home/miner/bitHopper/pool_class.py", line 29, in _parse
    self.rejects = self.bitHopper.db.get_rejects(self.index_name)
  File "/home/miner/bitHopper/database.py", line 487, in get_rejects
    self.curs.execute(sql)
sqlite3.OperationalError: no such table: slush

**Comment by c00w** [comment]
Shoot. Rewrote the db class and well it looks like it didn't work that well.

**Comment by c00w** [comment]
I added another fix. Is this still appearing?

**Comment by c00w** [comment]
I'm going to close this issue as it appears to be fixed.
