### ISSUE TITLE
BUG: backup_type = latehop (by MobiusL)

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#426]
bh.cfg
  Backup Type
backup_type = latehop

---

Traceback (most recent call last):
  File "bitHopper.py", line 311, in <module>
    main()
  File "bitHopper.py", line 281, in main
    bithopper_instance.select_best_server()
  File "bitHopper.py", line 155, in select_best_server
    backup_list = backup_list.sort(key=lambda pool: -1_pool['shares'])
  File "bitHopper.py", line 155, in <lambda>
    backup_list = backup_list.sort(key=lambda pool: -1_pool['shares'])
TypeError: string indices must be integers, not str

**Comment by MobiusL** [comment]
Same with earlyhop

**Comment by c00w** [comment]
Should be fixed now. I was sort of silly.
