### ISSUE TITLE
Stats website error

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#511]
Whenever I try to load the stats page this error is in the BH log and stats website is not working.

[15:06:27] invalid literal for int() with base 10: '60_60'
Traceback (most recent call last):
  File "C:\bithopper\website.py", line 276, in handle_start
    return use_site.handle(env,start_response)
  File "C:\bithopper\website.py", line 225, in handle
    'user':self.bitHopper.data.get_users()})
  File "C:\bithopper\data.py", line 49, in get_users
    if len(shares_time) > 0 and time.time()-max(shares_time) < int(self.user_dro
p_time):
ValueError: invalid literal for int() with base 10: '60_60'
/data

**Comment by c00w** [comment]
Update your bh.cfg to what it says in bh.cfg.default. Specifically the user_drop_time should say 3600 instead of 60*60

**Comment by Endeavour79** [comment]
works. thx
