### ISSUE TITLE
BUG: Threshold penalty for backup pools

### ISSUE THREAD

**Issue by paraipan** [c00w/bitHopper#518]
Setting "penalty:" for any backup pool doesn't seem to work here, bH ends with this error:

Traceback (most recent call last):
  File "bitHopper.py", line 311, in <module>
    main()
  File "bitHopper.py", line 281, in main
    bithopper_instance.select_best_server()
  File "bitHopper.py", line 134, in select_best_server
    server_list, backup_list = self.scheduler.select_best_server()
  File "/home/alex/bitHopper/scheduler.py", line 648, in select_best_server
    return server_list, self.select_backup_server()
  File "/home/alex/bitHopper/scheduler.py", line 100, in select_backup_server
    backup_servers.sort()
  File "/home/alex/bitHopper/pool_class.py", line 74, in **lt**
    rr_self += self.get('penalty', 0.0)
TypeError: unsupported operand type(s) for +=: 'float' and 'str'

**Comment by c00w** [comment]
What version are you using? I don't see a non wrapped self.get anywhere...

**Comment by paraipan** [comment]
oops, forgot i was using a "vintage" ver. (v0.2.5.5), maybe i should update and see if it's fixed, sorry :)
