### ISSUE TITLE
problem new install on ubuntu

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#537]
I followed the instructions in README for ubuntu but I get error messages constantly and I don't see hashes getting into /stats/

Here : 

Traceback (most recent call last):
  File "/home/btc/hopp/eventlet/hubs/hub.py", line 336, in fire_timers
    timer()
  File "/home/btc/hopp/eventlet/hubs/timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "/home/btc/hopp/work.py", line 227, in handle_store
    hook.notify(rpc_request, data, server)
  File "/home/btc/hopp/peak/util/plugins.py", line 58, in notify
    for hook in self.query(_args, *_kw):
  File "/home/btc/hopp/peak/util/plugins.py", line 68, in query
    yield hook(_args)
  File "/home/btc/hopp/plugins/rpcworklog/rpcworklog.py", line 26, in rpcWorkReport
    self.bitHopper.log_msg('RPC request [' + data[0][155:163] + "] submitted to " + server)
AttributeError: BitHopper instance has no attribute 'log_msg'
Traceback (most recent call last):
  File "/home/btc/hopp/eventlet/hubs/hub.py", line 336, in fire_timers
    timer()
  File "/home/btc/hopp/eventlet/hubs/timer.py", line 56, in **call**
    cb(_args, *_kw)
  File "/home/btc/hopp/work.py", line 227, in handle_store
    hook.notify(rpc_request, data, server)
  File "/home/btc/hopp/peak/util/plugins.py", line 58, in notify
    for hook in self.query(_args, *_kw):
  File "/home/btc/hopp/peak/util/plugins.py", line 68, in query
    yield hook(_args)
  File "/home/btc/hopp/plugins/rpcworklog/rpcworklog.py", line 26, in rpcWorkReport
    self.bitHopper.log_msg('RPC request [' + data[0][155:163] + "] submitted to " + server)
AttributeError: BitHopper instance has no attribute 'log_msg'

**Comment by hpcgam** [comment]
rapid solution:replace all "self.bitHopper.log_msg" with "pass" in rpcworklog.py
because plugin not support new logging system )

**Comment by Transisto** [comment]
I never used a password until now, will try just removing it.

**Comment by hpcgam** [comment]
On Mon, Dec 26, 2011 at 1:37 PM, Transisto
reply@reply.github.com
wrote:

**Comment by Transisto** [comment]
Thanks it work fine.

**Comment by hpcgam** [comment]
u welcome )
deepbit and bitcoin.lc works? in last commit mine_lp looks broken :(

**Comment by Transisto** [comment]
yep, deepbit does not get updated,  (800%+)

It it a bug from the latest commit ?

**Comment by hpcgam** [comment]
> It it a bug from the latest commit ?
> i dont know. may be bug. need seen code

**Comment by Transisto** [comment]
I had not this problem on windows on the previous one.

**Comment by hpcgam** [comment]
> I had not this problem on windows on the previous one.
> me too :) problem in last commit? may be

**Comment by c00w** [comment]
I updated the logging system and accidenatally broke a module. I'll fix it.

**Comment by c00w** [comment]
It should be fixed.

**Comment by hpcgam** [comment]
On Mon, Dec 26, 2011 at 4:44 PM, Colin Rice
reply@reply.github.com
wrote:

> It should be fixed.
> thanks )

**Comment by Transisto** [comment]
Updated,

Deepbit shares keep rising endlessly.

**Comment by c00w** [comment]
Okay, I'm going to close this issue and deal with that in #538.
