### ISSUE TITLE
Gevent 1.0dev issues

### ISSUE THREAD

**Issue by c00w** [c00w/bitHopper#583]
Traceback (most recent call last):
  File "/home/clr/bitHopper/work.py", line 116, in jsonrpc_call
    resp, content = http.request( url, 'POST', headers=header, body=request)
  File "/home/clr/bitHopper/httplib20_7_1/**init**.py", line 1437, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 1188, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 1124, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 955, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 989, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 787, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0dev-py2.7-linux-x86_64.egg/gevent/socket.py", line 474, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags, timeout=timeleft)  
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0dev-py2.7-linux-x86_64.egg/gevent/socket.py", line 446, in send
    self._wait(self._write_event)
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0dev-py2.7-linux-x86_64.egg/gevent/socket.py", line 283, in _wait
    assert watcher.callback is None, 'This socket is already used by another greenlet: %r' % (watcher.callback, )
AssertionError: This socket is already used by another greenlet: <built-in method switch of Greenlet object at 0x7f5eb0057910>
Traceback (most recent call last):
  File "/home/clr/bitHopper/work.py", line 116, in jsonrpc_call
    resp, content = http.request( url, 'POST', headers=header, body=request)
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 1437, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 1188, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 1154, in _conn_request
    conn.connect()
  File "/home/clr/bitHopper/httplib20_7_1/__init__.py", line 796, in connect
    raise socket.error, msg
error: [Errno 9] File descriptor was closed in another greenlet

**Comment by c00w** [comment]
Fixed.
