### ISSUE TITLE
end with "KeyError: 'btc'"

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#603]
latest...

Already up-to-date.
root@new:~/bitHopper# ./bitHopper.py
00:42:17|btcnet_wrapper: Trying to initialize btcnet_info repo
00:42:17|btcnet_wrapper: Checking if it has been cloned properly
00:42:17|btcnet_wrapper: It has been cloned properly
00:42:17|btcnet_wrapper: Updating btcnet_info
00:42:17|btcnet_wrapper: Done
gevent.monkey's warning: 'threading' is already imported

00:42:19|database: Cleaning Database
00:42:19|pool: pools-custom.cfg not found.
Traceback (most recent call last):
  File "./bitHopper.py", line 315, in <module>
    main()
  File "./bitHopper.py", line 235, in main
    bithopper_instance = BitHopper(options, config)
  File "./bitHopper.py", line 74, in **init**
    self.pool = pool.Pool_Parse(self)
  File "/root/bitHopper/pool.py", line 32, in **init**
    self.loadConfig()
  File "/root/bitHopper/pool.py", line 69, in loadConfig
    self.servers[pool] = pool_class.Pool(pool, dict(parser.items(pool)), self.bitHopper)
  File "/root/bitHopper/pool_class.py", line 14, in **init**
    self._parse(attribute_dict)
  File "/root/bitHopper/pool_class.py", line 17, in _parse
    self['shares'] = int(self.bitHopper.difficulty['btc'])
  File "/root/bitHopper/diff.py", line 32, in __getitem__
    return self.diff[key]
KeyError: 'btc'
root@new:~/bitHopper#

**Comment by c00w** [comment]
Try it now, should be fixed.

**Comment by Transisto** [comment]
look good, 

do you see new problems in this ? 

"...
gevent.monkey's warning: 'threading' is already imported

03:08:02|database: Cleaning Database
03:08:02|pool: pools-custom.cfg not found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/root/bitHopper/database.py", line 53, in __thread_init
    self.write_database()
  File "/root/bitHopper/database.py", line 81, in write_database
    time.sleep(60)
  File "/usr/lib/pymodules/python2.6/gevent/hub.py", line 71, in sleep
    switch_result = get_hub().switch()
  File "/usr/lib/pymodules/python2.6/gevent/hub.py", line 125, in get_hub
    raise NotImplementedError('gevent is only usable from a single thread')
NotImplementedError: gevent is only usable from a single thread

03:08:06|database: Cleaning Database
..."

**Comment by c00w** [comment]
Yeah, It should be fixed now.
