### ISSUE TITLE
error for latest, "ImportError: No module named git"

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#608]
Was working a1 for days on 2.6.  Giving 3.1.. another try gave me this : 

btc@ubuntu777:~/bitHopper$ ./bitHopper.py
Traceback (most recent call last):
  File "./bitHopper.py", line 35, in <module>
    import diff
  File "/home/btc/bitHopper/diff.py", line 9, in <module>
    from btcnet_wrapper import btcnet_info
  File "/home/btc/bitHopper/btcnet_wrapper.py", line 7, in <module>
    from git import Repo
ImportError: No module named git
btc@ubuntu777:~/bitHopper$ 

? I use git all the time to update.

**Comment by c00w** [comment]
You need to install pythongit. See the readme.
