### ISSUE TITLE
is this error normal

### ISSUE THREAD

**Issue by Transisto** [c00w/bitHopper#626]
21:05:20|website: Error in a wsgi function
21:05:20|website: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/btc/bitHopper/website.py", line 275, in handle_start
    return use_site.handle(env,start_response)
  File "/home/btc/bitHopper/website.py", line 284, in handle
    return self.bitHopper.work.handle(env, start_response)
  File "/home/btc/bitHopper/work.py", line 181, in handle
    server, auth = self.bitHopper.getwork_store.get_server(data[0][72:136])
TypeError: 'NoneType' object is not iterable

**Comment by c00w** [comment]
No and it should be fixed in the latest version.
