### ISSUE TITLE
Replace lpbot with dht

### ISSUE THREAD

**Issue by simonk83** [c00w/bitHopper#649]
Seems to have been down more than up for the past few days.   Not sure who looks after it to be honest though....

**Comment by c00w** [comment]
I think the IRC is dead. We have a dht based replacement with the backend coded. I'll add it to the todo list.

**Comment by simonk83** [comment]
Righto, thanks mate :)

**Comment by simonk83** [comment]
I assume this is related, but I finally got around to upgrading to the latest commit (I had to install Chrome to get the worker page working), and I'm seeing this:

21:53:50|work: Not in pool
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 325, in run
    result = self._run(_self.args, *_self.kwargs)
  File "G:\Handies\bitHopper\bitHopper\plugins\lpbot\lpbot.py", line 47, in run
    self.join()
  File "G:\Handies\bitHopper\bitHopper\plugins\lpbot\lpbot.py", line 209, in joi
n
    self.connection.join('#bithopper-lp')
  File "G:\Handies\bitHopper\bitHopper\plugins\lpbot\irclib.py", line 693, in jo
in
    self.send_raw("JOIN %s%s" % (channel, (key and (" " + key))))
  File "G:\Handies\bitHopper\bitHopper\plugins\lpbot\irclib.py", line 787, in se
nd_raw
    raise ServerNotConnectedError, "Not connected."
ServerNotConnectedError: Not connected.
<Greenlet at 0x319d2b0: <bound method LpBot.run of <plugins.lpbot.lpbot.LpBot in
stance at 0x031C3148>>> failed with ServerNotConnectedError

I assume it's just because the IRC is down, but thought I'd better post it anyway ;)

**Comment by c00w** [comment]
Yeah, thats the error. Just ignore it or disable lpbot.
