### ISSUE TITLE
Masterpool is Dead

### ISSUE THREAD

**Issue by Locky7** [c00w/bitHopper#653]
09:26:34|node: https://masterpool.eu/jsonstats
09:26:34|node: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\btcnet_info\node.py", line 120, in _poll
    headers, content = Http.request(self.name)
  File "C:\Python27\lib\site-packages\httplib2-0.7.4-py2.7.egg\httplib2__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Python27\lib\site-packages\httplib2-0.7.4-py2.7.egg\httplib2__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Python27\lib\site-packages\httplib2-0.7.4-py2.7.egg\httplib2__init__.py", line 1268, in _conn_request
    conn.connect()
  File "C:\Python27\lib\site-packages\httplib2-0.7.4-py2.7.egg\httplib2__init__.py", line 1019, in connect
    raise socket.error, msg
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by c00w** [comment]
removed from btcnet_info
