### ISSUE TITLE
New change difficulty and WRONG difficulty AGAIN

### ISSUE THREAD

**Issue by asdlsd** [c00w/bitHopper#671]
in my BH difficulty is 1,577,913 now (

**Comment by TimLinton** [comment]
isn't that shares?

**Comment by asdlsd** [comment]
see previos my issues

**Comment by TimLinton** [comment]
Why not post your previous issues in the previous thread?

**Comment by c00w** [comment]
I've hardcoded it again. It updates on my side after 60 seconds to the correct difficulty. There may be something wierd happening.

**Comment by c00w** [comment]
pip install btcnet_info --upgrade

**Comment by asdlsd** [comment]
not result (

**Comment by c00w** [comment]
Thats not good, let me doublecheck btcnet_info.

**Comment by asdlsd** [comment]
What about check? New difficulty comes soon.

**Comment by c00w** [comment]
The library converges to the new difficulty in 40 seconds. I'm not sure why bitHopper isn't picking up the updated difficulty.

**Comment by asdlsd** [comment]
this bag only in my BH or for all?

**Comment by asdlsd** [comment]
today is new difficulty.
pip install btcnet_info --upgrade
restart
and!!! difficulty is 1,508,589 in my BH
ah... I would have this difficulty 2 weeks ago ((

**Comment by c00w** [comment]
bitHopper picks up the new difficulty in 60 seconds. There is nothing wrong on our end. Wait for it to synchronize. It won't be correct instantly upon startup. 

If it doesn't pickup the difficulty within 120 seconds then I recommend deleting the btcnet_info folder inside the bitHopper directory.

**Comment by asdlsd** [comment]
difficulty not change (.

my action:
del btcnet_info (it was empty)
pip install btcnet_info --upgrade
restart
wait 5 minits
((
nothing changes, difficulty is 1,508,589

**Comment by asdlsd** [comment]
my BH installed on VPS. I can give you access, if it interesting for you.

**Comment by c00w** [comment]
I can poke around it this weekend, send me an email ricec2@rpi.edu. How are you determining what difficulty bitHopper is using?

**Comment by asdlsd** [comment]
difficulty stay is 1,508,589 (

**Comment by c00w** [comment]
I verified that bitHopper was updating the difficulty on your vps. The display of current shares is probably broken in some manner. I'll take a look.

**Comment by asdlsd** [comment]
difficulty stay is 1,508,589 ((

**Comment by c00w** [comment]
Delete bitHopper and redownload. something is messed up with your btcnet_info folder.

**Comment by asdlsd** [comment]
ok. del and install
difficulty stay is 1,000,000

**Comment by asdlsd** [comment]
pip install btcnet_info --upgrade
restart
and difficulty is 1,508,589 (((((((

**Comment by c00w** [comment]
Update bitHopper, I made it output the difficulty every time it updates. Can you check the output after the second update?

**Comment by asdlsd** [comment]
it after update
root@Debian-60-squeeze-64-minimal:/opt/bitHopper# git pull
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 14 (delta 9), reused 14 (delta 9)
Unpacking objects: 100% (14/14), done.
From git://github.com/c00w/bitHopper
   5fb94a2..eb7df91  master     -> origin/master
   2ad87f1..4fc0374  0.3.2      -> origin/0.3.2
Updating 5fb94a2..eb7df91
Fast-forward
 diff.py |    2 ++
 1 files changed, 2 insertions(+), 0 deletions(-)

it after ferst start
08:57:27|bitHopper: Debugging Enabled
08:57:27|database: Cleaning Database
08:57:27|pool: pools-custom.cfg not found.
08:57:27|database: Cleaning Database
08:57:27|pool: Please configure some pools!
08:57:27|pool: Go to localhost:8337/worker
08:57:27|pool: Then restart bitHopper
08:57:27|node: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info/node.py", line 120, in _poll
    headers, content = Http.request(self.name, headers={'Connection':'close'})
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1230, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 890, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused

08:57:27|node: http://localhost:9332
08:57:28|lp: LP Module Load
08:57:28|plugin: Loading Config Files
08:57:28|pool: pools-custom.cfg not found.
08:57:28|database: Cleaning Database
08:57:28|plugin: Plugin loading mode: manual
08:57:28|plugin: Loading Plugins
08:57:28|plugin: hookexample failed reading main config file: No option 'hookexample' in section: 'plugins'
08:57:28|plugin: hookexample has been disabled
08:57:28|plugin: payouts has been disabled
08:57:28|plugin: blockaccuracy has been disabled
08:57:28|plugin: poolblocks has been disabled
08:57:28|plugin: test has been disabled
08:57:28|plugin: lpbot has been disabled
08:57:28|plugin: rpcworklog loaded
08:57:28|plugin: lpdump has been disabled
08:57:28|plugin: backdoor has been disabled
08:57:28|apiangel: Check interval: 60
08:57:28|apiangel: Re-Incarnate interval: 3600
08:57:28|plugin: apiangel loaded
08:57:28|plugin: poclbm has been disabled
08:57:28|plugin: lpworkbench has been disabled
08:57:28|bitHopper: Selecting scheduler: DefaultScheduler
08:57:28|work: Error with a work.get() http request: Only absolute URIs are allowed. uri = alex
08:57:28|api: alex api error:'api_method'
08:57:28|work: Error with a work.get() http request: Only absolute URIs are allowed. uri = arsbitcoin
08:57:28|api: arsbitcoin api error:'api_method'
08:57:28|work: Error with a work.get() http request: Only absolute URIs are allowed. uri = gpumax
08:57:28|api: Share estimation disabled for: GPUmax (PPS)
08:57:28|api: gpumax:   0

and difficulty is 1,000,000 ))

**Comment by c00w** [comment]
Can you wait longer? There should have been a couple lines printed that looked like:

21:34:53|diff: Difficulty for nmc:518525.941302
21:34:53|diff: Difficulty for ixc:236.115
21:34:53|diff: Difficulty for btc:1508589
21:34:53|diff: Difficulty for geg:1.63535
21:34:53|diff: Difficulty for scc:8108.883
21:34:53|diff: Difficulty for i0c:448.348

**Comment by Locky7** [comment]
I agree with c00w. Moreover, there are a few lines referring to pools that should now be removed, are you on the latest clone?  Otherwise, I notice that I no longer have that same difficulty issue and considered it resolved.

I am running a recent clone using the windows git client 1.0...loving it! Beautiful work Colin

**Comment by asdlsd** [comment]
"Moreover, there are a few lines referring to pools that should now be removed"
what is file?

**Comment by Locky7** [comment]
delete everything but the user.cfg, bh.cfg, and worker.cfg and clone the repository...  Someone please correct me if I am wrong..but that is what I would do.  Again, I had the same issue as you so I, too, hard codded it...  c00w has now fixed it.  I just did FRESH install. ;)

**Comment by asdlsd** [comment]
i reinstall BH
pip install btcnet_info --upgrade
and

09:44:44|bitHopper: Debugging Enabled
09:44:44|database: Cleaning Database
09:44:44|pool: pools-custom.cfg not found.
09:44:44|database: Cleaning Database
09:44:44|pool: Please configure some pools!
09:44:44|pool: Go to localhost:8337/worker
09:44:44|pool: Then restart bitHopper
09:44:44|node: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info/node.py", line 120, in _poll
    headers, content = Http.request(self.name, headers={'Connection':'close'})
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1230, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 890, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused

09:44:44|node: http://localhost:9332
09:44:44|diff: Difficulty for i0c:448.348
09:44:44|diff: Difficulty for scc:8108.883
09:44:44|diff: Difficulty for btc:1508589
09:44:44|diff: Difficulty for geg:1.63535
09:44:44|diff: Difficulty for nmc:518525.941302
09:44:44|diff: Difficulty for ixc:236.115
09:44:44|node_handle: Potential type error None, Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info/node_handle.py", line 210, in duration
    duration += float(result.group(index)) \* prefix_multiplier(prefix)
TypeError: float() argument must be a string or a number

09:44:44|node_handle: Potential type error None, Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info/node_handle.py", line 210, in duration
    duration += float(result.group(index)) \* prefix_multiplier(prefix)
TypeError: float() argument must be a string or a number

09:44:45|lp: LP Module Load

is came
i will wait...

**Comment by asdlsd** [comment]
difficulty stay is 1,508,589
what files should be in dir "btcnet_info"?

**Comment by c00w** [comment]
It should automatically download them. Its not a great solution and I should just update everything to version 0.3.2.

**Comment by asdlsd** [comment]
greats! I install (clean) 0.3.2 and:

**Comment by asdlsd** [comment]
09:27:19|ServerLogic|rebuild_servers: No valid pools configured
09:27:20|**init**|get_work_unit: Root 889c0db81664a06c5cf663cecf60edd97ae8acd274d97525b415c9ee45ab962b not in <bitHopper.Tracking.getwork_store.Getwork_Store instance at 0x3449440>
09:27:20|**init**|get_work_unit: Root 4a25abca44114847d101645b5a2dce29dcd2e96d0a996f60c780314bf573d8dc not in <bitHopper.Tracking.getwork_store.Getwork_Store instance at 0x3449440>
09:27:20|**init**|get_work_unit: Root cc8959754b1f7821640480e4eb77b37dc37268816ef8ed4944e542d4bf240f4c not in <bitHopper.Tracking.getwork_store.Getwork_Store instance at 0x3449440>
09:27:22|**init**|get_work_unit: Root 70a47d159dc5a572c76f613628c288b4afa08d5740d3ef1b9ba05925f1a60fed not in <bitHopper.Tracking.getwork_store.Getwork_Store instance at 0x3449440>
09:27:23|**init**|mine: Traceback (most recent call last):
  File "/opt/bitHopper/bitHopper/Mining_Site/**init**.py", line 43, in mine
    return mine_real(environ, start_response)
  File "/opt/bitHopper/bitHopper/Mining_Site/**init**.py", line 88, in mine_real
    content, headers = bitHopper.Network.get_work(headers = headers)
  File "/opt/bitHopper/bitHopper/Network/**init**.py", line 64, in get_work
    server, username, password = bitHopper.Logic.get_server()
  File "/opt/bitHopper/bitHopper/Logic/**init**.py", line 31, in get_server
    return _select(list(generate_tuples(ServerLogic.get_server())))
  File "/opt/bitHopper/bitHopper/Logic/ServerLogic.py", line 201, in get_server
    return _select(Servers).name
  File "/opt/bitHopper/bitHopper/Logic/ServerLogic.py", line 18, in _select
    raise ValueError("No valid pools")
ValueError: No valid pools

**Comment by asdlsd** [comment]
in web (IP:8337):
{"id": 1, "result": null, "error": {"message": "Invalid Request"}}

**Comment by asdlsd** [comment]
... i undestand - IP:8339
i create miners
but dont create workers - web is empty

**Comment by c00w** [comment]
Go to localhost:8339 and add some workers on the worker page. Make sure to add some pools which are pps.

**Comment by asdlsd** [comment]
worker page is empty

**Comment by aaferrari** [comment]
asdlsd, I had the same problem as you with the empty worker page, until after doing some testing I discovered that the problem was the gevent module that was outdated, so I downloaded the latest version and install it.
As a side note: If after upgrading gevent you find that at review in http://localhost:8337/worker note that although is empty (or with only a couple of pools, as happened to me) then you should delete the directory where btcnet_info is installed (in my case is "c:\python\lib\site-packages\btcnet_info-0.1.2.22-py2.7.egg") and re-execute the "python setup.py install" command.

**Comment by asdlsd** [comment]
Swiche, thanks... after your actions worker page is not empty... but it was one time, after restart BH worker page is empty. (OS Debian 6)
Now i install ubunta 12.04, but problem is still... worker page is empty (... and on previos BH difficulty is 1,508,589.

**Comment by aaferrari** [comment]
Curious, I use Windows XP and for the moment I can see the worker page after restart BitHopper. Anyway, this particular problem seems to be caused when the files that are inside the directory "%PYTHON%/Lib/site-packages/btcnet_info-0.1.2.22-py2.7.egg/btcnet_info/pools" are empty because the BitHopper modifies often those files and with the older version of gevent, those files remain empty for some strange reason (you can check this by running the program with the <tt>--debug</tt> parameter and accessing at the worker page should appear in the console something like <tt>Worker_Page|worker page: Ignoring &lt;Pool None, None, None&gt;</tt> or going directly to that directory to see if the files have 0 bytes), so if you followed the steps that I leave in the previous message, then only thing that occurs to me is that another process (or some function of BitHopper) is leaving empty those files.
With respect to the "static difficulty" of Bitcoin, I can not do much for now because since several months ago that not update the program and code of the same has changed a lot since then so I'm still re-configuring it from scratch (and attempting to familiarize myself with the program and its source code). But meanwhile you can try to update the difficulty value manually editing the file "btc" that is in ".../Btcnet_info/coins" and changing the value <tt>value</tt> by the current (make sure you have closed the program before doing this).

**Comment by asdlsd** [comment]
python run.py --debug

08:37:16|**init**|print_btcni_ver: btcnet_info version 0.1.2.22
08:37:16|node|_poll: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info-0.1.2.22-py2.7.egg/btcnet_info/node.py", line 120, in _poll
    headers, content = Http.request(self.name, headers={'Connection':'close'})
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1236, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.namebit.org

08:37:16|node|_poll: http://www.namebit.org/
08:37:16|ServerLogic|rebuild_servers: No valid pools configured
08:37:16|node|_poll: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/btcnet_info-0.1.2.22-py2.7.egg/btcnet_info/node.py", line 120, in _poll
    headers, content = Http.request(self.name, headers={'Connection':'close'})
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1544, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1294, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1230, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.7.4-py2.7.egg/httplib2/__init__.py", line 1019, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused

08:37:16|node|_poll: https://www.arsbitcoin.com/api.php
08:37:21|ServerLogic|rebuild_servers: No valid pools configured

yes and acsess to worker page:

08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>
08:38:12|Worker_Page|worker: Ignoring <Pool None, None, None>

but in "%PYTHON%/Lib/site-packages/btcnet_info-0.1.2.22-py2.7.egg/btcnet_info/pools" several files is not empty...

**Comment by c00w** [comment]
Hmmm. I'll figure it out. I think ignoring means that we didn't selected the pool because it was invalid. Add eligius and mtred. I know we have them listed as pps pools

**Comment by c00w** [comment]
And by invalid I mean it was a prop pool with too many shares to be worth mining.

**Comment by asdlsd** [comment]
@Add eligius and mtred. I know we have them listed as pps pools@ 

how to do it?

**Comment by c00w** [comment]
Ignoring means we are ignoring the pool because it doesn't have a valid pool name. If this is happening you should update btcnet_info, prerably by running pip install --uprade btcnet_info

**Comment by c00w** [comment]
Go to localhost:8339 and add worker information

**Comment by asdlsd** [comment]
after update btcnet_info for ver. 0.1.2.27 difficulty is correct. I still use old BH (not 3.2)...
in 3.2 after "python run.py" i get error:
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    import bitHopper
ImportError: No module named bitHopper

**Comment by c00w** [comment]
Are you doing python run.py from the bitHopper directory.

**Comment by asdlsd** [comment]
yes, but directorys name is bithopper032

**Comment by asdlsd** [comment]
rename directory - not result

**Comment by c00w** [comment]
Hmmm. What is in the bitHopper folder inside of the bitHopper(or bitHopper032) folder.

**Comment by c00w** [comment]
Also you are running from the master branch not 0.3.2 right?

**Comment by asdlsd** [comment]
git clone git://github.com/c00w/bitHopper.git
and regulary 
git pull

**Comment by c00w** [comment]
Ok.

**Comment by asdlsd** [comment]
is it master?

**Comment by c00w** [comment]
That is master.

**Comment by c00w** [comment]
What version of python are you running?

**Comment by asdlsd** [comment]
Python 2.7.3

**Comment by c00w** [comment]
Hmmm. I have absolutely no idea. Can you zip up your bitHopper 0.3.2 folder and email it to me? colin@daedrum.net

**Comment by asdlsd** [comment]
ок

**Comment by asdlsd** [comment]
i reinstall BH 
git clone git://github.com/c00w/bitHopper.git
and start ok

**Comment by asdlsd** [comment]
but old problem with stats was still... please see (adress send on email)

**Comment by c00w** [comment]
Was this resolved when I ssh'd into your server? I can't remember

**Comment by asdlsd** [comment]
now working on old BH... but on Deepbit incorrect hopping

PS. hohoho... difficulty is 1000 now ( ... update library?

22.01.2013, 01:42, "Colin Rice" notifications@github.com:

**Comment by c00w** [comment]
Yeah

sudo pip install --upgrade btcnet_info

**Comment by asdlsd** [comment]
Hi.  I did this yestoday, but not result... diff is 1000 (( What about Deepbit... they not hopping for now? 28.01.2013, 02:10, "Colin Rice" notifications@github.com:Yeahsudo pip install --upgrade btcnet_info— Reply to this email directly or view it on GitHub.

**Comment by c00w** [comment]
You are using the old bitHopper. I don't think it does anything dumb but can you tell me the exact version so I an check it out and confirm?

**Comment by asdlsd** [comment]
exact version??? where can i see it? 28.01.2013, 16:31, "Colin Rice" notifications@github.com:You are using the old bitHopper. I don't think it does anything dumb but can you tell me the exact version so I an check it out and confirm?— Reply to this email directly or view it on GitHub.

**Comment by c00w** [comment]
I'm assuming you are using git, so the output of 
    git log -1
Otherwise it should be in the zip file name.

**Comment by asdlsd** [comment]
not gitbut from arh v0.3.1.6.tar.gz  28.01.2013, 20:02, "Colin Rice" notifications@github.com:I'm assuming you are using git, so the output of  git log -1 Otherwise it should be in the zip file name.— Reply to this email directly or view it on GitHub.
