### ISSUE TITLE
error: [Errno 10061]

### ISSUE THREAD

**Issue by Endeavour79** [c00w/bitHopper#675]
0:34:28|node: Traceback (most recent call last):
  File "C:\bithopper\btcnet_info\node.py", line 120, in _poll
    headers, content = Http.request(self.name, headers={'Connection':'close'})
  File "C:\Users\Admin\AppData\Roaming\Python\Python27\site-packages\httplib2__init__.py", line 1445, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Users\Admin\AppData\Roaming\Python\Python27\site-packages\httplib2__init__.py", line 1197, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\Admin\AppData\Roaming\Python\Python27\site-packages\httplib2__init__.py", line 1133, in _conn_request
    conn.connect()
  File "C:\Users\Admin\AppData\Roaming\Python\Python27\site-packages\httplib2__init__.py", line 799, in connect
    raise socket.error, msg
error: [Errno 10061] No connection could be made because the target machine actively refused it.

**Comment by c00w** [comment]
This happens, pools close things etc... Don't worry about it.
