### ISSUE TITLE
Problem with 0.3.2

### ISSUE THREAD

**Issue by Delta1977** [c00w/bitHopper#689]
Hello, 

i made a fresh install as you described in the readme on a Ubuntu 12.04 where the old version runs without problems,

version 0.3.2 dont  starts up, with this message;

02:59:11|**init**|mine: Traceback (most recent call last):
  File "/root/bitHopper/bitHopper/Mining_Site/**init**.py", line 43, in mine
    return mine_real(environ, start_response)
  File "/root/bitHopper/bitHopper/Mining_Site/**init**.py", line 88, in mine_real
    content, headers = bitHopper.Network.get_work(headers = headers)
  File "/root/bitHopper/bitHopper/Network/**init**.py", line 64, in get_work
    server, username, password = bitHopper.Logic.get_server()
  File "/root/bitHopper/bitHopper/Logic/**init**.py", line 31, in get_server
    return _select(list(generate_tuples(ServerLogic.get_server())))
  File "/root/bitHopper/bitHopper/Logic/ServerLogic.py", line 201, in get_server
    return _select(Servers).name
  File "/root/bitHopper/bitHopper/Logic/ServerLogic.py", line 18, in _select
    raise ValueError("No valid pools")
ValueError: No valid pools

The /workes comes up, theres nothing to change or add.

The /stats comes with an 404 error .

Whats wrong??

**Comment by c00w** [comment]
Update your gevent version.

**Comment by c00w** [comment]
Actually I take that back. You need to upgrade your version of btcnet_info. One solution is to redownload bithopper and refollow the instructions in the readme since I improved the install script.

**Comment by c00w** [comment]
Another user says you should try running bitHopper as non root. It doesn't need root permissions
