### ISSUE TITLE
Setup Failure

### ISSUE THREAD

**Issue by jcsjourney2008** [c00w/bitHopper#695]
I followed your setup instructions for Windows to the letter but i am unable to get it to run. I cannot find the install.py file that you refer to and when i run "python setup.py install" in CMD (with and without admin) it will always return with - No module named 'setuptools' (This has been installed correctly!)

**Comment by c00w** [comment]
Sorry about that, I changed the instructions to refer to python setup.py install. It sounds like setup tools hasn't been installed. Can you try reinstalling it and seeing if that fixes the problem? I'll try installing bitHopper on my end and see if that works better.

**Comment by c00w** [comment]
I installed bitHopper on a clean vm and it worked for me with the updated instructions. I think you just forgot to install setuptools.

**Comment by jcsjourney2008** [comment]
I have tried installing all of them about 6 times each and it will still show it missing. I have also restarted multiple times and it will not register as installed. Is this an issue with the fact that i have Win 7 Ultimate x64?

**Comment by c00w** [comment]
It shouldn't be. What happens when you just run python.exe and then import setuptools?

**Comment by jcsjourney2008** [comment]
I was able to get the file from here: http://packages.python.org/an_example_pypi_project/setuptools.html
To work. I was able to get a result by right clicking and editing with IDLE and then running the module from there to get this result: 
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

> > > ================================ RESTART ================================
> > > 
> > > Setuptools version 0.6c11 or greater has been installed.
> > > (Run "ez_setup.py -U setuptools" to reinstall or upgrade.)

**Comment by jcsjourney2008** [comment]
Acually after i found that was of installing via IDLE i decided to open your "setup.py" file and "Run Module." I was able to get this result:

Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

> > > ================================ RESTART ================================

Traceback (most recent call last):
  File "C:\Users\Journeyx\Downloads\c00w-bitHopper-v0.3.2-43-ga6880ce (1)\c00w-bitHopper-a6880ce\setup.py", line 16, in <module>
    'flask',
  File "C:\Python27\lib\distutils\core.py", line 140, in setup
    raise SystemExit, gen_usage(dist.script_name) + "\nerror: %s" % msg
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by jcsjourney2008** [comment]
FIXED IT! After messing around more with it i was able to get it working. This is what my CMD got me:

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Journeyx>cd C:\c

C:\c>C:\Python27\python.exe setup.py install
running install
running bdist_egg
running egg_info
creating dummy_bithopper_install.egg-info
writing requirements to dummy_bithopper_install.egg-info\requires.txt
writing dummy_bithopper_install.egg-info\PKG-INFO
writing top-level names to dummy_bithopper_install.egg-info\top_level.txt
writing dependency_links to dummy_bithopper_install.egg-info\dependency_links.tx
t
writing manifest file 'dummy_bithopper_install.egg-info\SOURCES.txt'
reading manifest file 'dummy_bithopper_install.egg-info\SOURCES.txt'
writing manifest file 'dummy_bithopper_install.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\EGG-INFO
copying dummy_bithopper_install.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-I
NFO
copying dummy_bithopper_install.egg-info\SOURCES.txt -> build\bdist.win32\egg\EG
G-INFO
copying dummy_bithopper_install.egg-info\dependency_links.txt -> build\bdist.win
32\egg\EGG-INFO
copying dummy_bithopper_install.egg-info\requires.txt -> build\bdist.win32\egg\E
GG-INFO
copying dummy_bithopper_install.egg-info\top_level.txt -> build\bdist.win32\egg\
EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\dummy_bithopper_install-0.0.9-py2.7.egg' and adding 'build\bdist.
win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing dummy_bithopper_install-0.0.9-py2.7.egg
Copying dummy_bithopper_install-0.0.9-py2.7.egg to c:\python27\lib\site-packages

Adding dummy-bithopper-install 0.0.9 to easy-install.pth file

Installed c:\python27\lib\site-packages\dummy_bithopper_install-0.0.9-py2.7.egg
Processing dependencies for dummy-bithopper-install==0.0.9
Searching for flask
Reading http://pypi.python.org/simple/flask/
Reading http://github.com/mitsuhiko/flask/
Best match: Flask 0.9
Downloading http://pypi.python.org/packages/source/F/Flask/Flask-0.9.tar.gz#md5=
4a89ef2b3ab0f151f781182bd0cc8933
Processing Flask-0.9.tar.gz
Running Flask-0.9\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appdata\loc
al\temp\easy_install-cxe7lc\Flask-0.9\egg-dist-tmp-rw3rxj
warning: no files found matching '_' under directory 'tests'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'do
cs'
warning: no previously-included files matching '_.pyc' found under directory 'te
sts'
warning: no previously-included files matching '_.pyo' found under directory 'te
sts'
warning: no previously-included files matching '_.pyc' found under directory 'ex
amples'
warning: no previously-included files matching '*.pyo' found under directory 'ex
amples'
no previously-included directories found matching 'docs_build'
no previously-included directories found matching 'docs_themes.git'
Adding flask 0.9 to easy-install.pth file

Installed c:\python27\lib\site-packages\flask-0.9-py2.7.egg
Searching for btcnet-info>=0.1.2.27
Reading http://pypi.python.org/simple/btcnet_info/
Reading http://pypi.python.org/simple/btcnet_info/github.com/c00w/btcnet_info
Best match: btcnet-info 0.1.2.27
Downloading http://pypi.python.org/packages/source/b/btcnet_info/btcnet_info-0.1
.2.27.tar.gz#md5=c1513a942438bbe0b25ed7f611dab738
Processing btcnet_info-0.1.2.27.tar.gz
Running btcnet_info-0.1.2.27\setup.py -q bdist_egg --dist-dir c:\users\journeyx\
appdata\local\temp\easy_install-lnxvny\btcnet_info-0.1.2.27\egg-dist-tmp-or9gc_
warning: no files found matching 'coins*' under directory 'btcnet_info'
warning: no files found matching 'exchanges*' under directory 'btcnet_info'
warning: no files found matching 'difficulty_sites*' under directory 'btcnet_in
fo'
warning: no files found matching 'pools*' under directory 'btcnet_info'
zip_safe flag not set; analyzing archive contents...
btcnet_info.objects: module references **file**
Adding btcnet-info 0.1.2.27 to easy-install.pth file

Installed c:\python27\lib\site-packages\btcnet_info-0.1.2.27-py2.7.egg
Searching for mechanize
Reading http://pypi.python.org/simple/mechanize/
Reading http://wwwsearch.sourceforge.net/mechanize/
Best match: mechanize 0.2.5
Downloading http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.t
ar.gz
Processing mechanize-0.2.5.tar.gz
Running mechanize-0.2.5\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appda
ta\local\temp\easy_install-tfyqfz\mechanize-0.2.5\egg-dist-tmp-rbxylm
warning: no files found matching 'output' under directory 'test\functional_tests
_golden'
Adding mechanize 0.2.5 to easy-install.pth file

Installed c:\python27\lib\site-packages\mechanize-0.2.5-py2.7.egg
Searching for requests>=0.14.1
Reading http://pypi.python.org/simple/requests/
Reading http://python-requests.org
Reading https://github.com/kennethreitz/requests
Best match: requests 0.14.2
Downloading http://pypi.python.org/packages/source/r/requests/requests-0.14.2.ta
r.gz#md5=488508ba3e8270992ad5b3fb54d364ca
Processing requests-0.14.2.tar.gz
Running requests-0.14.2\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appda
ta\local\temp\easy_install-ufrkyb\requests-0.14.2\egg-dist-tmp-dnl92m
warning: no files found matching 'tests*.'
zip_safe flag not set; analyzing archive contents...
requests.certs: module references **file**
Adding requests 0.14.2 to easy-install.pth file

Installed c:\python27\lib\site-packages\requests-0.14.2-py2.7.egg
Searching for Jinja2>=2.4
Reading http://pypi.python.org/simple/Jinja2/
Reading http://jinja.pocoo.org/
Best match: Jinja2 2.6
Downloading http://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.6.tar.gz#md
5=1c49a8825c993bfdcf55bb36897d28a2
Processing Jinja2-2.6.tar.gz
Running Jinja2-2.6\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appdata\lo
cal\temp\easy_install-hrxoxq\Jinja2-2.6\egg-dist-tmp-tfrp83
warning: no previously-included files matching '_' found under directory 'docs_
build'
warning: no previously-included files matching '_.pyc' found under directory 'ji
nja2'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'ji
nja2'
warning: no previously-included files matching '*.pyo' found under directory 'do
cs'
Adding jinja2 2.6 to easy-install.pth file

Installed c:\python27\lib\site-packages\jinja2-2.6-py2.7.egg
Searching for Werkzeug>=0.7
Reading http://pypi.python.org/simple/Werkzeug/
Reading http://werkzeug.pocoo.org/
Reading http://trac.pocoo.org/repos/werkzeug/trunk
Best match: Werkzeug 0.8.3
Downloading http://pypi.python.org/packages/source/W/Werkzeug/Werkzeug-0.8.3.tar
.gz#md5=12aa03e302ce49da98703938f257347a
Processing Werkzeug-0.8.3.tar.gz
Running Werkzeug-0.8.3\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appdat
a\local\temp\easy_install-woevr7\Werkzeug-0.8.3\egg-dist-tmp-tnsgt1
warning: no files found matching '_' under directory 'werkzeug\debug\templates'
warning: no files found matching '_' under directory 'tests'
warning: no previously-included files matching '_.pyc' found under directory 'do
cs'
warning: no previously-included files matching '_.pyo' found under directory 'do
cs'
warning: no previously-included files matching '_.pyc' found under directory 'te
sts'
warning: no previously-included files matching '_.pyo' found under directory 'te
sts'
warning: no previously-included files matching '_.pyc' found under directory 'ex
amples'
warning: no previously-included files matching '_.pyo' found under directory 'ex
amples'
no previously-included directories found matching 'docs_build'
Adding werkzeug 0.8.3 to easy-install.pth file

Installed c:\python27\lib\site-packages\werkzeug-0.8.3-py2.7.egg
Searching for httplib2
Reading http://pypi.python.org/simple/httplib2/
Reading http://code.google.com/p/httplib2/
Best match: httplib2 0.7.6
Downloading http://httplib2.googlecode.com/files/httplib2-0.7.6.zip
Processing httplib2-0.7.6.zip
Running httplib2-0.7.6\setup.py -q bdist_egg --dist-dir c:\users\journeyx\appdat
a\local\temp\easy_install-pzkn2o\httplib2-0.7.6\egg-dist-tmp-88gkey
zip_safe flag not set; analyzing archive contents...
httplib2.**init**: module references **file**
Adding httplib2 0.7.6 to easy-install.pth file

Installed c:\python27\lib\site-packages\httplib2-0.7.6-py2.7.egg
Searching for gevent==1.0b2
Best match: gevent 1.0b2
Adding gevent 1.0b2 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for setuptools==0.6c11
Best match: setuptools 0.6c11
Processing setuptools-0.6c11-py2.7.egg
Adding setuptools 0.6c11 to easy-install.pth file
Installing easy_install-script.py script to C:\Python27\Scripts
Installing easy_install.exe script to C:\Python27\Scripts
Installing easy_install.exe.manifest script to C:\Python27\Scripts
Installing easy_install-2.7-script.py script to C:\Python27\Scripts
Installing easy_install-2.7.exe script to C:\Python27\Scripts
Installing easy_install-2.7.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\setuptools-0.6c11-py2.7.egg
Searching for greenlet==0.3.4
Best match: greenlet 0.3.4
Adding greenlet 0.3.4 to easy-install.pth file

Using c:\python27\lib\site-packages
Finished processing dependencies for dummy-bithopper-install==0.0.9

C:\c>C:\Python27\python.exe run.py
00:47:59|**init**|print_btcni_ver: btcnet_info version 0.1.2.27
Check learning started
00:48:11|ServerLogic|rebuild_servers: No valid pools configured
00:48:11|Learning|poke_deepbit: No workers for deepbit. Disabling machine learni
ng
00:48:16|ServerLogic|rebuild_servers: No valid pools configured

**Comment by c00w** [comment]
Awesome. The next step is to configure some pools. 

Do the C:\Python27\python.exe run.py

And then open up localhost:8339 in a web browser.
Click the workers link and add some pools.

I recomend eligius, mtred or arsbitcoin. Make sure that you have some workers on pools with fair (PPLNS, PPS) schemes since bitHopper currently won't give out work where it's not profitable to mine.

**Comment by jcsjourney2008** [comment]
I go that part setup and i moved on to configure my miner. I set it up to point to that url you said and BitHopper is showing me trying to connect but the miner keeps saying that it cannot connect. I am using Phoenix miner with the following config file: 

[general]
backend = http://localhost:8337
autodetect = +cl -cpu -cuda

[cl:0:0]
kernel = opencl
AGGRESSION = 6
WORKSIZE = 128

Am i missing something??

**Comment by c00w** [comment]
What workers have you added to bitHopper? Also what version of Phoenix are you using?

**Comment by jcsjourney2008** [comment]
I have added coinotron, eclipsemc, slush, mtred, and deepbit. I set my miner, Pheonix 2.0.0, to login with http://user:x@localhost:8337

It logs in and works until the hopper goes to switch pools then it cannot connect.

**Comment by c00w** [comment]
Hmmm. This may be a bug with stratum support dieing in a fire.

**Comment by jcsjourney2008** [comment]
And this will be fixed how?

**Comment by c00w** [comment]
I'll download pheonix 2.0.0 and see exactly what its doing. I recomend switching to poclbm cgminer or bfgminer for the time being until I can figure out what its doing.
