### ISSUE TITLE
python run.py run error

### ISSUE THREAD

**Issue by WKNiGHT-** [c00w/bitHopper#700]
When trying to run python run.py

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    import bitHopper
  File "/home/hop/bitHopper/bitHopper/**init**.py", line 19, in <module>
    import bitHopper.Network
  File "/home/hop/bitHopper/bitHopper/Network/**init**.py", line 17, in <module>
    session = requests.session(config=config)
TypeError: session() takes no arguments (1 given)

**Comment by ghost** [comment]
Same issue after following all the setup steps for linux. 

Finished processing dependencies for dummy-bithopper-install==0.0.9
:~/bitHopper# python run.py
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    import bitHopper
  File "/root/bitHopper/bitHopper/**init**.py", line 19, in <module>
    import bitHopper.Network
  File "/root/bitHopper/bitHopper/Network/**init**.py", line 17, in <module>
    session = requests.session(config=config)
TypeError: session() takes no arguments (1 given)

**Comment by c00w** [comment]
So this should be fixed. It turns out one of the libraries we use changed its interface and we broke. I'm hitting another bug on my test system though. Probably related to my current setup. So I pushed the patch for this issue.

Also I made github start sending me emails again because it looks like I don't check it often enough. Sorry in the response time delay.

**Comment by WKNiGHT-** [comment]
Yup it started up. Does the bug look something like this?

17:26:15|**init**|print_btcni_ver: btcnet_info version 0.1.2.34
Check learning started
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/home/bh/bitHopper/bitHopper/LongPoll_Listener/Learning.py", line 89, in poke_deepbit
    bitHopper.Network.send_work_lp(url, username, password, 'deepbit')
  File "/home/bh/bitHopper/bitHopper/Network/__init__.py", line 103, in send_work_lp
    _, server_headers = send_work(url, username, password)
  File "/home/bh/bitHopper/bitHopper/Network/__init__.py", line 69, in send_work
    return request(url, body = body, headers= headers, method=method, timeout = timeout)
  File "/home/bh/bitHopper/bitHopper/Network/**init**.py", line 36, in request
    r = session.request(method, url=url, data=body, headers=headers, timeout=timeout, prefetch=True, verify=False)
TypeError: request() got an unexpected keyword argument 'prefetch'
<Greenlet at 0x2db6e10: poke_deepbit> failed with TypeError

**Comment by WKNiGHT-** [comment]
Another repeating error kept scrolling through. This is when your miner is trying to connect to bithopper. Only way to kill this scroll is by killing the PID

17:50:42|**init**|get_work: Traceback (most recent call last):
  File "/home/bh/bitHopper/bitHopper/Network/**init**.py", line 86, in get_work
    content, server_headers = send_work( url, username, password, headers, request, timeout=1)
  File "/home/bh/bitHopper/bitHopper/Network/**init**.py", line 69, in send_work
    return request(url, body = body, headers= headers, method=method, timeout = timeout)
  File "/home/bh/bitHopper/bitHopper/Network/**init**.py", line 36, in request
    r = session.request(method, url=url, data=body, headers=headers, timeout=timeout, prefetch=True, verify=False)
TypeError: request() got an unexpected keyword argument 'prefetch'

**Comment by c00w** [comment]
This should be fixed now. 3e2b8f12dd1cbfa6a889da7fc0befac733162bb7

**Comment by c00w** [comment]
Is this fixed?

**Comment by WKNiGHT-** [comment]
Yes, Sorry this should be moved to resolved.
