### ISSUE TITLE
After adding Slush, Deepbit and Ozcoin only. Continue No Valid pools configured error

### ISSUE THREAD

**Issue by WKNiGHT-** [c00w/bitHopper#702]
06:15:33|ServerLogic|rebuild_servers: No valid pools configured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/home/wknight/bitHopper/bitHopper/Network/__init__.py", line 76, in get_work
    server, username, password = bitHopper.Logic.get_server()
  File "/home/wknight/bitHopper/bitHopper/Logic/**init**.py", line 23, in get_server
    return _select(list(generate_tuples(ServerLogic.get_server())))
  File "/home/wknight/bitHopper/bitHopper/Logic/ServerLogic.py", line 201, in get_server
    return _select(Servers).name
  File "/home/wknight/bitHopper/bitHopper/Logic/ServerLogic.py", line 18, in _select
    raise ValueError("No valid pools")
ValueError: No valid pools
<Greenlet at 0x327aaf0: get_work(headers={'user_agent': 'cgminer 2.9.5'})> failed with ValueError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 438, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 425, in run_application
    self.process_result()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 414, in process_result
    for data in self.result:
  File "/home/wknight/bitHopper/bitHopper/Mining_Site/**init**.py", line 97, in mine_real
    content, headers = g.get(timeout=0.1)
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 331, in get
    raise self._exception
ValueError: No valid pools
<WSGIServer fileno=4 address=0.0.0.0:8337>: Failed to handle request:
  request = POST / HTTP/1.1 from ('10.0.1.18', 49347)
  application = <function mine at 0x2e62488>

<socket fileno=18 sock=192.168.1.14:8337 peer=192.168.1.13:49348 timeout=900.0>: Invalid HTTP method: '{"id": 3997, "method": "mining.subscribe", "params": []}\n'
06:15:38|ServerLogic|rebuild_servers: No valid pools configured
06:15:43|ServerLogic|rebuild_servers: No valid pools configured

**Comment by c00w** [comment]
So this is because there are no good pools to mine. deepbit, and slush are only mined when it is profitable. Not sure about ozcoin.

**Comment by WKNiGHT-** [comment]
OZCOIN which is DGM should be listed as a backup pool. With the admin page you cannot set this to backup. Slush and Deepbit are listed as Info. So if you have OZCOIN has a backup pool. Deepbit and Slush. You will still get 

14:27:06|ServerLogic|rebuild_servers: No valid pools configured

**Comment by c00w** [comment]
Okay, thats broken. It looks like we are listing ozcoin as a backup pool. I'm assuming you have some workers added for ozcoin. I'll add some myself and see whats up.

**Comment by WKNiGHT-** [comment]
That is correct. Also Slush showed to find a block and bithopper didn’t not hop to it since its listed as info. I am assuming the same will happen to deepbit but I will have to keep a eye on this for confirmation

**Comment by c00w** [comment]
Slush shouldn't be shown as an info pool. Are you looking at the old style admin interface?

**Comment by c00w** [comment]
Also there was a bug with dgm not being hopped onto. I fixed it.

**Comment by WKNiGHT-** [comment]
Ozcoin is now working :). Yes I was looking at the old style admin interface to see what it should be hopping too. It never did go to slush. :8339/pool is just a blank page

**Comment by c00w** [comment]
Okay, the slush window is quite small, so sometimes we miss blocks.

**Comment by c00w** [comment]
I'm going to close this as it is now fixed.
